---
- name: Create Qbittorrent Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ qbittorrent_config_directory }}"
    - "{{ qbittorrent_download_directory }}"
    - "{{ qbittorrent_movie_directory }}"
    - "{{ qbittorrent_tv_directory }}"
    # - "{{ qbittorrent_watch_directory }}"

- name: Qbittorrent Docker Container
  docker_container:
    name: qbittorrent
    image: "{{ qbittorrent_docker_image }}"
    pull: true
    volumes:
      - "{{ qbittorrent_config_directory }}:/config:rw"
      - "{{ qbittorrent_download_directory }}:/downloads:rw"
      - "{{ qbittorrent_movie_directory }}:/movies:rw"
      - "{{ qbittorrent_tv_directory }}:/tv:rw"
      # - "{{ qbittorrent_watch_directory }}:/watch:rw"
    ports:
      - "{{ qbittorrent_webui_port }}:8081"
      - "{{ qbittorrent_external_port }}:16881"
      - "{{ qbittorrent_external_port }}:16881/udp"
    env:
      TZ: "{{ qbittorrent_timezone }}"
      PUID: "{{ qbittorrent_user_id }}"
      PGID: "{{ qbittorrent_group_id }}"
      WEBUI_PORT: "{{ qbittorrent_webui_port }}"
    restart_policy: unless-stopped
    memory: "{{ qbittorrent_memory }}"
    labels:
      traefik.enable: "{{ qbittorrent_available_externally }}"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
      traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "8081"
